### ISSUE TITLE
Upstream all necessary ARTIQ changes

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/ndscan#1]
[Currently](https://github.com/m-labs/artiq/commit/ef934ad9580b4061e5f0c5a262aafc9f3c082aa0), a few patches to ARTIQ proper are required to use ndscan. A branch from a while ago with all the required commits can be found here: https://github.com/m-labs/artiq/compare/master...dnadlinger:ndscan. A good portion of them have already been merged upstream, sometimes with slight changes.

The biggest missing chunks are RID namespaces and custom argument UI support.

**Comment by dnadlinger** [comment]
Appending to datasets: https://github.com/m-labs/artiq/pull/1271

**Comment by dnadlinger** [comment]
Current diff:

```
$ git show-ref m-labs/master ion-trap/master
b50ad712f58fdb6de25a6770e00bedaa8fee2596 refs/remotes/ion-trap/master
9c9dc3d0efac1af8bc601c0f10fb44c5094a1dfc refs/remotes/m-labs/master

$ git diff m-labs/master ion-trap/master -- ":(exclude)artiq/coredevice" ":(exclude)artiq/examples" ":(exclude)artiq/frontend/artiq_ddb_template.py" ":(exclude)artiq/frontend/artiq_flash.py" ":(exclude)artiq/gateware" ":(exclude)conda" > oxford-artiq.diff
```

[oxford-artiq.diff](https://github.com/OxfordIonTrapGroup/ndscan/files/5011053/oxford-artiq.diff.txt)

**Comment by dtcallcock** [comment]
@dnadlinger Are there any plans to do this in the near term?

**Comment by Jemetzner** [comment]
@dnadlinger can we get a new patch for artiq6?

**Comment by dnadlinger** [comment]
@dtcallcock: I hope to address the bulk of the diff this weekend (or whenever I get this one paper draft out).

@Jemetzner: Updated above comment for some commit two weeks ago. (Probably applies to the 6.0 branc, but I didn't check.)

**Comment by dtcallcock** [comment]
Great news.  Thanks for the diff.  Much appreciated.

**Comment by dnadlinger** [comment]
See https://github.com/m-labs/artiq/issues/1614 for a discussion on RID namespaces – I am considering dropping support for them in artiq_master, and making ndscan save data into explicitly namespaced keys (e.g. `ndscan.rid_123456.points…`) instead.

After we've decided on a way to go for this, the remainder of the patch should be easily upstreamed (save for scheduler `idle` support, which is only coincidentally contained in the patch).

**Comment by ljstephenson** [comment]
@dnadlinger any chance there's a more recent diff against upstream artiq? I clobbered something together using the old diff but there were merge conflicts and I'm in a slightly broken state (well, artiq is, I'm ok).

**Comment by dnadlinger** [comment]
@charlesbaynham Added an up-to-date patch, but it's still based on ARTIQ from August last year – I'm mostly writing these days, and people are only slowly porting stuff to RISC-V/….

**Comment by charlesbaynham** [comment]
Thank you @dnadlinger ! Much appreciated

**Comment by dnadlinger** [comment]
https://github.com/OxfordIonTrapGroup/ndscan/pull/289 removes the reliance on master-side rid-based dataset namespaces, and thus makes upstreaming the rest of the diff very feasible.

**Comment by hartytp** [comment]
@dnadlinger nice work on this!

It looks like pretty much the entire remainder of the patch is now upstreamed? One thing I think is still missing is removing this warning https://github.com/m-labs/artiq/blob/715bff3ebfa4125f0d7bcd43eec11da3c1577403/artiq/master/worker_db.py#L161-L162 which spams the log with ndscan

**Comment by dnadlinger** [comment]
@hartytp Thankfully, this is now _no longer an ndscan issue (tm)_. I agree, though, the warning is overzealous, and should be removed. We've been running with that warning patched out since time immemorial, as it seems overzealous, and I haven't heard of anybody shooting themselves in the foot w.r.t. reproducibility, as it is quite easy to write code in a principled way that avoids any issues. At the same time, IIRC Robert seems to strongly prefer keeping the check, although I couldn't find the related discussion on a quick search (do you perhaps remember where we discussed this?). I wonder what's the best approach here – if all else fails, some kind of config option?

**Comment by dnadlinger** [comment]
README update/ARTIQ 6 patches to follow.

**Comment by hartytp** [comment]
> At the same time, IIRC Robert seems to strongly prefer keeping the check, although I couldn't find the related discussion on a quick search (do you perhaps remember where we discussed this?).

The most recent discussion on the subject I recall was on IRC around https://chat.m-labs.hk/m-labs/channels/town-square/ko4u6yq913b59rp7zxdcyyizcy

**Comment by hartytp** [comment]
> @hartytp Thankfully, this is now no longer an ndscan issue (tm).

Agreed. I would only make the obvious addition here that (at least last time I tried) running `ndscan` without this warning suppressed resulted in the log being sufficiently heavily spammed with spurious warnings that it constituted a non-negligible usability issue. This is likely to trip new users up.

> I wonder what's the best approach here – if all else fails, some kind of config option?

Something like an `overwrite_archived` parameter for `get_dataset` to be explicit? Until something like that's merged, a sentence in the readme might avoid some confusion for new users.

**Comment by hartytp** [comment]
> I wonder what's the best approach here – if all else fails, some kind of config option?

Another option might be to only emit the warning if the value has actually changed. Or did we consider that and rule it out for some reason?
