### ISSUE TITLE
plots: Colour bar for 2D scans

### ISSUE THREAD

**Issue by RHanley1** [OxfordIonTrapGroup/ndscan#101]
When a 2D scan is performed, a color-map is used to display the data. Is it possible to add a scale bar to the applet so that one can read the data values before post-processing?

**Comment by dnadlinger** [comment]
Would be very, very useful, yes; just like #102.

This should be fairly easy to add, as only changes to https://github.com/OxfordIonTrapGroup/ndscan/blob/master/ndscan/plots/image_2d.py should be necessary.

**Comment by NearConstant** [comment]
I'm also having this issue, was there any progress on it?

**Comment by dnadlinger** [comment]
Fixed in #329, result channel label added in https://github.com/OxfordIonTrapGroup/ndscan/commit/b8f12b40aca7b6a0cf19801a1838d20aa4d278bb.
