### ISSUE TITLE
OnlineFit: sinusoid & decaying_sinusoid

### ISSUE THREAD

**Issue by pathfinder49** [OxfordIonTrapGroup/ndscan#109]
It would be grat if OnlineFit supported oitg.fitting.sinusoid and oitg.fitting.decaying_sinusoid

**Comment by dnadlinger** [comment]
Done by CML and https://github.com/OxfordIonTrapGroup/ndscan/commit/628bc34d3dd9f578583f0a119030b981f31cc037.
