### ISSUE TITLE
Save non-scanned parameters

### ISSUE THREAD

**Issue by RHanley1** [OxfordIonTrapGroup/ndscan#134]
It currently appears that only paramaters which are scanned are saved with the associated run_id. How does one save the parameters which aren't scanned?

**Comment by dnadlinger** [comment]
The complete information, including scan mode, overrides, default values used, etc. is stored in the `ndscan_params` ARTIQ argument, which ARTIQ in turn saves to the `arguments` field in `expid`.

As these things go, it's fairly readable (`expid -> arguments -> ndscan_param -> overrides` is just a dict of parameter FQNs to overridden paths and their values).

We might want to add a convenience method for pretty-printing them to a module of data analysis routines, though, along with other useful functions like parsing a 2D scan result channel into a 2D array, etc.

**Comment by RHanley1** [comment]
This doesn't seem to be in the dictionary returend by oitg.results. Am I looking in the wrong place?

**Comment by dnadlinger** [comment]
It should be in `r["expid"]`.

**Comment by RHanley1** [comment]
Thankyou!

**Comment by RHanley1** [comment]
The format of the ["overides"] seems to be a string instead of a dictionary. What is the best way to convert back to a dictionary? Using PYON?

**Comment by dnadlinger** [comment]
Yep, it's a PYONValue parameter (all of ndscan_params, actually) so decoding it as PYON would be the thing to do.
