### ISSUE TITLE
Overwriting Tlist(TList(T)) attributes crashes scans silently

### ISSUE THREAD

**Issue by pathfinder49** [OxfordIonTrapGroup/ndscan#159]
There seems to be very buggy behaviour of list of lists in the kernel. Unfortunatly, I haven't managed to reproduce this behaviour in artiq (though I expect this to be the root cause).

The following experiment demonstrates the issue:

```python3
from ndscan.experiment import *

class NDScanTest(ExpFragment):
    def build_fragment(self):
        self.setattr_device("core")
        self.setattr_param("test_param",
                           FloatParam,
                           "test param",
                           default=30 * us,
                           unit="us")

    def host_setup(self):
        self.a = [[1.1]]

    @kernel
    def run_once(self):
        print("krun")
        # print(0.)  # <----- uncommenting this line makes the bug dissapear
        print(self.a)
        self.a = self.rpc()
        print(self.a)

    def rpc(self) -> TList(TList(TFloat)):
        a = [[2.2]]
        return a
```

Scaning the test parameter will print: 
```
krun
[[1.1]]
[[2.2]]
krun
```
The second scan point is started ,but not completed. no errors are shown in the dashboard or master logs. Aside from the missing print messages no indication is given that the experiment crashed.

**Comment by dnadlinger** [comment]
Closing, as this is not related to ndscan; this is m-labs/artiq#1394 causing memory corruption, at which point all bets are off.

**Comment by dnadlinger** [comment]
Now fixed in ARTIQ master.
