### ISSUE TITLE
plots: Show multi-axis 1D scan as vertical stack of plots

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/ndscan#200]
The multiple axes superimposed on each other are mostly just obnoxious in the presence of noise (and/or errorbars).

**Comment by AUTProgram** [comment]
I assume by multi-axis you mean multiple y-axes for different result channels? If so, it might be useful to make the proposed behaviour optional. We find it helpful sometimes (especially with two-qubit scans) to have two channels on same plot (possibly with different y-limits on left and right) as it makes it easier to compare relative magnitudes of values in channels.

**Comment by dnadlinger** [comment]
Not currently, but it would be nice to have.

**Comment by sotirova** [comment]
@dnadlinger shall we discuss the best way to implement this?

**Comment by dnadlinger** [comment]
I'm not sure there is much to discuss in general. :P

You first need to figure out how to best implement this within pyqtgraph. I'm sure there is some example code floating around on the internet.

Once you have done that, the piece of code to change is https://github.com/OxfordIonTrapGroup/ndscan/blob/master/ndscan/plots/xy_1d.py. You should be able to re-use most of the code; just need to make sure to target the right plot panel for all the annotations, etc. once it's been split up into more than one.
