### ISSUE TITLE
Allow setattr_param to require a dataset entry is present

### ISSUE THREAD

**Issue by Timboski** [OxfordIonTrapGroup/ndscan#209]
I would like to call `setattr_param` without providing a numeric default value within the Fragment.

I can currently get a default value from the dataset, though I also have to provide a fallback value which is used if the data entry is not present.

I would rather it raised a `KeyError` if the data is missing. This mirrors `get_dataset` behaviour.
(Or even a less generic exception)

**Comment by dnadlinger** [comment]
What would be displayed in the user interface if the dataset is not present?

**Comment by Timboski** [comment]
I would be happy with the same behaviour as `get_dataset`.
The UI pane does not even launch. I just get a `KeyError` in the Log window.
Similarly - clicking `Recompute all arguments` (if UI is already open) just gives the same Log error.

If the UI launched but made it obvious that it had failed, it would be even better.
This is a separate issue though (as already happens with `get_dataset`).

**Comment by Timboski** [comment]
Thinking about it, I could just use `get_dataset` to get the default.
Something like:
`self.setattr_param(...blah..., default=get_dataset('key'))`

This is probably even preferable as the exception comes from the client code rather than the framework.

**Comment by pathfinder49** [comment]
> Thinking about it, I could just use `get_dataset` to get the default.

That's the pattern I tend to use. (To go full circle, `get_dataset()` takes an optional fallback if the key doesn't exist.)

**Comment by hartytp** [comment]
This gets the job done, but feels rather unergonomic -- if one encounters the pattern `self.setattr_param(f"dataset('foo', defalult={self.get_dataset('foo')}")` it's not immediately obvious what's going unless one is familiar with this issue.

The automatic creation of datasets feels like a nice feature during the development / testing phase, but at production time it can be as much of a footgun as a help. Maybe an ergonomic way of enabling it / disabling it would be helpful? Maybe if the default is `None` then raise a clear exception if the dataset is missing?

**Comment by AUTProgram** [comment]
I believe there is actually a side effect when providing the default via `default=self.get_dataset("string")`. In this case, ndscan will not link the parameter to the dataset, so can't update its value from applet. Additionally, the value will not be recomputed when a scan is interrupted by a higher-level experiment and then resumes. So the desired behaviour of forcing the existence of a dataset while retaining the features of the `default="dataset(...)"` syntax can't be achieved by using `self.get_dataset` directly. A workaround that I am using currently is to do something like
```
param_dataset = "string"
param_default = self.get_dataset(param_dataset)

self.setattr_param("param", FloatParam, default=f"dataset('{param_dataset}', {param_default})")
```
However, this feels more complicated than it should be. So I think it would be nice if ndscan supported this use case.
