### ISSUE TITLE
Changing unit in setattr_param_rebind does not set scale

### ISSUE THREAD

**Issue by Timboski** [OxfordIonTrapGroup/ndscan#210]
Changing the `unit` in `setattr_param_rebind` changes the unit that is displayed in the UI, however it does not change the scale to match.

`self.setattr_param(...blah..., unit="us")`
`self.setattr_param_rebind(...blah..., default=100 * ms, unit="ms")`

The UI shows `100000 ms`

As a workaround, the scale must also be set:
`self.setattr_param_rebind(...blah..., default=100 * ms, unit="ms", scale=ms)`

**Comment by dnadlinger** [comment]
This is a bit non-trivial to implement in the current, generic version of `setattr_param_rebind`. Patches welcome, though.

**Comment by JammyL** [comment]
I think there are two options to implement while keeping things general.

1. Don't deepcopy the param. `setattr_param_like` performs `new_param = deepcopy(template_param)`. If we instead reinitialise based upon parameters in the `template_param`, then we can force the scale to check against the units again.

2. (I prefer this one) Add a `reinit` function to the params. This would perform any operations like rechecking the scale that are required for a particular `Param`. For the `StringParam` this would just `pass`.

Thoughts @dnadlinger?

**Comment by dnadlinger** [comment]
I'd prefer 1), i.e. getting away from `deepcopy` and directly `setattr`-ing members in the first place. This is a pretty strong code smell; other objects shouldn't be messing around with the internal state.

**Comment by JammyL** [comment]
> I'd prefer 1), i.e. getting away from `deepcopy` and directly `setattr`-ing members in the first place. This is a pretty strong code smell; other objects shouldn't be messing around with the internal state.

The benefit of keeping the `deepcopy` is that using the `Param`'s current state is very easy. Meaning that ommiting any new args such as the `unit`, `scale`, or `min`/`max`  and just using the "default" is done for you.

If we don't `deepcopy`, then either we need to depend on the `__init__` `args` being recovereable from the current `Param` object, or we store them explictly (or a third thing I haven't thought of)

**Comment by dnadlinger** [comment]
> Meaning that omiting any new args such as the unit, scale, or min/max and just using the "default" is done for you.

That was indeed the reason for using the deepcopy hack in the first place, but as you found out, messing directly with the internal state of an object tends to produce weird results.

Just storing a dict of all the args in the constructor and merging that with any kwargs should be a bullet-proof, clean, easy to understand solution.

**Comment by dnadlinger** [comment]
Probably fixed in https://github.com/OxfordIonTrapGroup/ndscan/pull/315.
