### ISSUE TITLE
Toggling result channels in applets

### ISSUE THREAD

**Issue by AUTProgram** [OxfordIonTrapGroup/ndscan#235]
Whenever I have a result channel that I do not want to be displayed all the time in applet of experiment, I have so far been passing `display_hints={"priority": -1}` for the respective parameter in build stage. This means that result channel is available for post-analysis, but not shown in applet. This is not very flexible as it requires editing the source code to change which channels are displayed in applet. Is there an easier way of achieving this behaviour?
If not, it would be nice to be able to toggle result channels on and off directly in applet. I think this is implemented for 2D scans, but not 1D? Something like right-clicking and then ticking those result channels which should be displayed.

**Comment by AUTProgram** [comment]
Just realised that this was already raised in #26, I think. Feel free to close.

**Comment by dnadlinger** [comment]
Yep, apparently #26 already exists – thanks for the archeology!
