### ISSUE TITLE
External installation not possible using conda for artiq components

### ISSUE THREAD

**Issue by ljstephenson** [OxfordIonTrapGroup/ndscan#246]
Currently it isn't possible (or I haven't found the appropriate workaround) to install ndscan externally with conda:

- ndscan requires python>=3.8
- `conda create -n test python=3.8 llvmlite-artiq` fails because binaries haven't been built for python>3.7 (https://github.com/m-labs/artiq/issues/1687)

Obviously this is only necessary for the master; I haven't tried a more minimal dashboard only install, or using Nix (even using WSL requires security waivers at NIST, let alone Linux...)

What (broadly) is the current setup you guys are using?

**Comment by dnadlinger** [comment]
For clients Conda, with everything on 3.8, rebuilt on a custom channel if not available elsewhere. (Not sure if anybody is using a full master install on Windows, though.)

**Comment by ljstephenson** [comment]
OK, cool. I'll probably roll back a few commits as a hack to get things working while I figure that out. Thanks!

**Comment by dnadlinger** [comment]
Seems like the issue should be resolved upstream now, though.
