### ISSUE TITLE
xy_1d error: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by hartytp** [OxfordIonTrapGroup/ndscan#247]
Using a results channel with error bars I get the following backtrace generated by the applet

```
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/ndscan/plots/xy_1d.py", line 201, in _update_points
print:    s.update(x_data, points)
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/ndscan/plots/xy_1d.py", line 76, in update
print:    self.view_box.addItem(self.error_bar_item)
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 409, in addItem
print:    self.updateAutoRange()
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 890, in updateAutoRange
print:    childRange = self.childrenBounds(frac=fractionVisible)
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 1402, in childrenBounds
print:    bounds = self.mapFromItemToView(item, item.boundingRect()).boundingRect()
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ErrorBarItem.py", line 156, in boundingRect
print:    self.drawPath()
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ErrorBarItem.py", line 86, in drawPath
print:    xs = fn.interweaveArrays(x, x)
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/pyqtgraph/functions.py", line 694, in interweaveArrays
print:    size = sum(x.size for x in args)
print:  File "/miniconda/envs/devenv/lib/python3.8/site-packages/pyqtgraph/functions.py", line 694, in <genexpr>
print:    size = sum(x.size for x in args)
print:AttributeError: 'list' object has no attribute 'size'
```

I have done a small amount of digging. It looks like the pyqtgraph `setData` method explicitly requires a np array (https://github.com/pyqtgraph/pyqtgraph/blob/b9e079b10cc95ec7344c2da95b5ac6827fb02cc5/pyqtgraph/graphicsItems/ErrorBarItem.py#L37) , but some debug prints tell me we're passing in a list. 

There is an alternative dead (?) codepath here https://github.com/OxfordIonTrapGroup/ndscan/blob/9d46a98df2abafa61640b6d8085a59491b240441/ndscan/plots/xy_1d.py#L47 that converts the x / y data into an array. Doing the same for the other codepath seems to resolve this issue.

Having talked to @dnadlinger it sounds like the x / y data ndscan uses will indeed be lists. So, by not casting to arrays we are violating the contract with pyqtgraph. Best guess is that this only ever worked by accident and some modification to pyqtgraph caused it to break (I don't feel like bisecting, so haven't confirmed...)

After discussion with @dnadlinger we've agree that we should fix this by casting x / y data to arrays for both code paths.

**Comment by hartytp** [comment]
One thing I don't understand here is why I only see this when I add error bars to the experiment.

**Comment by dnadlinger** [comment]
> One thing I don't understand here is why I only see this when I add error bars to the experiment.

Looking at the backtrace you sent to me, this occurred somewhere in ErrorBarItem.

**Comment by hartytp** [comment]
@dnadlinger yes, that was only part of a much longer backtrace (with an exception for each data point on the scan). IIRC there were exceptions raised from both calls to `setData` so this wasn't just related to the error bars, but I might have been wrong about that. Either way, this fix does seem appropriate since it brings the ndscan code inline with the pyqtgraph docs.
