### ISSUE TITLE
Result files: include all parameter values

### ISSUE THREAD

**Issue by pathfinder49** [OxfordIonTrapGroup/ndscan#262]
As far as I'm aware, the experiment result files currently do not contain parameter values that have been loaded from a dataset. It would simplify experiment analysis (and experiment archeology) to include all parameters directly in the results files. Currently we need to look these values up in influxDB...

Would including all parameter values directly in the results file (in addition-to/instead-of the dataset) make the files excessivly large? Am I missing some other reason this isn't a good idea?

**Comment by dnadlinger** [comment]
They are archived by ARTIQ as normal under `archive/`, so no InfluxDB needed. You can reconstruct all the used parameter values from that and the parameter schemata, which are all saved.

**Comment by dnadlinger** [comment]
If somebody felt inclined, they could write a "parameter tree viewer", though, that reads in all the schemata and instances, applies the overrides, and presents the results in some UI – might be handy from time to time.
