### ISSUE TITLE
get_last for all result sinks

### ISSUE THREAD

**Issue by hartytp** [OxfordIonTrapGroup/ndscan#273]
@dnadlinger what is the preferred means of getting the last value from a `ResultChannel` within an experiment? is it from the sink (accessed via `self.channel.sink`)? 

If so, one thing that is a bit unergonomic is that ['ArraySink'](https://github.com/OxfordIonTrapGroup/ndscan/blob/a1bb5246ec417b2377a373928917c1f54cbb98b6/ndscan/experiment/result_channels.py#L36) does not have a `get_last()` method like all the other `sink` subtypes. This means that `get_last()` isn't available when `Fragment`s are using inside subscans.

Would you merge a PR that added `get_last` to `ArraySink` and possibly also `ResultSink`?

**Comment by dnadlinger** [comment]
In the current design, the preferred means would likely be to manually introduce an extra member somewhere that stores the value. What is the use case? The top-level/subscan/… `run()`-type methods typically return a dictionary with all the values – is that an alternative in your case.

The background here is that the separate sinks are conceptually intended as dependency injections points into the fragment tree, where "dependency" in this case is the result handling strategy. For instance, it is probably a sensible default to just log all the individual readout counts for most experiments so you can go back to the HDF5 files later and see if the histograms are sensible, etc. However, this produces quite a bit of data and RPC traffic, which might not be desirable when a fragment is used as part of a more complex experiment. Another instance might be extra analysis data that might be difficult to compute, might require expensive extra hardware calls, etc. In such cases, that more complex caller experiment could just not set the sink on the result channel and the data wouldn't be stored. The implementation could check `is_muted()` on the result channel and avoid even computing and broadcasting the data in the first place.

Truth to be told, I have been wondering lately whether the automatic enumeration and dependency injection scheme (which has worked out well for parameters) is worth it for result channels – it might be cleaner to always manually pass them up the chain.

That being said, this is a larger and somewhat orthogonal discussion, though; I'd be happy to merge a `get_last()` PR for uniformity, although its use probably shouldn't be encouraged.

**Comment by hartytp** [comment]
> In the current design, the preferred means would likely be to manually introduce an extra member somewhere that stores the value. What is the use case? The top-level/subscan/… run()-type methods typically return a dictionary with all the values – is that an alternative in your case.

Maybe there is a better way of doing this (if so, I'd be interested to hear ideas!), but...the exact use case here was a sideband thermometry experiment. This has a `run_once` method which takes one point on each of the red/blue sidebands and then stores the measured temperature as a result channel. We wanted a way of getting the RSB/BSB populations out of our readout fragments.

**Comment by dnadlinger** [comment]
I suppose the "cleanest" solution to this in the current design would be to absorb and, assuming you want to store the individual populations for debugging, re-export the result channel in the thermometry fragment. The thermometry fragment would set the sink of the individual sideband pulse fragment results to something that keeps track of the value and forwards it to its own redefined results channels (which themselves might or might not have a sink attached, depending on the caller of the thermometry experiment).

IIRC, the functionality to "absorb" results is used for subscans, but might not be properly exported with a public, non-underscore name.

**Comment by hartytp** [comment]
> I suppose the "cleanest" solution to this in the current design would be to absorb and, assuming you want to store the individual populations for debugging, re-export the result channel in the thermometry fragment.

Could you elaborate on what you mean by "absorb" in this context?

**Comment by dnadlinger** [comment]
By "absorb", I mean stopping the result channel from bubbling up to the top level and being "consumed" (handled) by the scan runner. Rather, the thermometry fragment would handle the raw results, e.g. by setting up a LastValueSink for the subfragment result channels to keep them around.

Whether or not it then also puts the subfragment results into its own `rsb_p` and `bsb_p` channels to help the user in debugging or just exposes the derived quantities is then up to the the caller fragment. If this is a frequent pattern, we might of course want to add a helper function to ndscan that handles this "re-export the sub-fragment results but add a point to tap into it" pattern.

This is pretty much how I envisioned this working when I designed the result handling system, but as usual (what with having written this while trying to get data) I just never got around to actually nailing down how the API for that should look. The implementation will be very simple; subscans already do this:

https://github.com/OxfordIonTrapGroup/ndscan/blob/a1bb5246ec417b2377a373928917c1f54cbb98b6/ndscan/experiment/subscan.py#L239

**Comment by hartytp** [comment]
That works nicely. Thanks @dnadlinger

**Comment by hartytp** [comment]
NB the behaviour here changed a bit in https://github.com/OxfordIonTrapGroup/ndscan/commit/2f9e36f9acdf89eba0335e471dd4a7bac2910414 If I've understood correctly, detaching a subfragment means that - as well as its results not propagating - it is no longer automatically setup / cleaned up.

So, back to the original use-case: I have a sideband thermometry experiment with two readout subfragments, one for each of the RSB/BSB. At each point in my scan I want to calculate a value for `nbar` based on the BSB/RSB populations.

> I suppose the "cleanest" solution to this in the current design would be to absorb and, assuming you want to store the individual populations for debugging, re-export the result channel in the thermometry fragment. The thermometry fragment would set the sink of the individual sideband pulse fragment results to something that keeps track of the value and forwards it to its own redefined results channels (which themselves might or might not have a sink attached, depending on the caller of the thermometry experiment).

If I've understood correctly (apologies if not!) in pseudocde, I think this suggestion looks like is something along the lines of:
```python
def build_fragment(self):
    ...

    self.rsb_readout.detach()
    self.bsb_readout.detach()

    self.rsb_readout.p.set_sink(nd.LastValueSink())
    self.bsb_readout.p.set_sink(nd.LastValueSink())

    self.rsb_readout.p_err.set_sink(nd.LastValueSink())
    self.bsb_readout.p_err.set_sink(nd.LastValueSink())

    self.stattr_result(
            "p_rsb",
            nd.FloatChannel,
            description="rsb height",
            min=0.0,
            max=1.0,
        )
        self.setattr_result(
            "p_rsb_err",
            min=0.0,
            display_hints={"error_bar_for": self.p_rsb.path},
        )

    self.stattr_result(
            "p_bsb",
            nd.FloatChannel,
            description="bsb height",
            min=0.0,
            max=1.0,
        )
        self.setattr_result(
            "p_bsb_err",
            min=0.0,
            display_hints={"error_bar_for": self.p_bsb.path},
        )

# these are only needed to setup/cleanup the detached subfragments
def host_setup(self):
    super().host_setup()
    self.rsb_readout.host_setup()
    self.bsb_readout.host_setup()

@kernel
def device_setup(self):
    self.rsb_readout.device_setup()
    self.bsb_readout.device_setup()
    self.device_setup_subfragments()

@kernel
def run_once(self):
    ....
    self.push_results()

@rpc(flags={"async"})
def push_results(self):
    p_rsb = self.readout_rsb.p.sink.get_last()
    p_bsb = self.readout_bsb.p.sink.get_last()
    p_rsb_err = self.readout_rsb.p_err.sink.get_last()
    p_bsb_err = self.readout_bsb.p_err.sink.get_last()

   self.p_rsb.push(p_rsb)
   self.p_bsb.push(b_bsb)
   self.rsb_err.push(rsb_err)
   self.bsb_err.push(bsb_err)
```

That feels like a lot of work / boilerplate to do something relatively simple...

> In the current design, the preferred means would likely be to manually introduce an extra member somewhere that stores the value. What is the use case? 

That's an option, but it feels a bit unsatisfactory to manually duplicate the information already in the sink. It's also a bit messy to implement.

> That being said, this is a larger and somewhat orthogonal discussion, though; I'd be happy to merge a get_last() PR for uniformity, although its use probably shouldn't be encouraged.

I've come around to the view that this is the right path here and will spin up a PR in a bit.

**Comment by dnadlinger** [comment]
We could abstract away the boilerplate code for the general use case of "run these fragments, re-export the results, and add some extra derived results", similar to `AggregateExpFragment` (or even as an extension thereof).
