### ISSUE TITLE
Visualisation of multiple results channels

### ISSUE THREAD

**Issue by sotirova** [OxfordIonTrapGroup/ndscan#274]
We need to be able to visualise many results channels, e.g. 5-10, and the current plotting (lots of lines on top of each other) is a little hard to see.

@dnadlinger Can we please discuss the best way of extending ndscan to do this?

**Comment by dnadlinger** [comment]
Is this #200?

**Comment by sotirova** [comment]
Whoops, yes, it is (as a first step). Will move the discussion there.
