### ISSUE TITLE
Syntax error in saved ndscan_params in results file

### ISSUE THREAD

**Issue by vmsch** [OxfordIonTrapGroup/ndscan#276]
There is a problem with how the 'always_shown' arguments are saved, causing an error message when running json.loads() on the ndscan_params saved in 'expid' in the results file

What I run:
```
dict_str=json.loads(f["expid"][()])
dict_str_2=dict_str['arguments']['ndscan_params']
b=json.loads(dict_str_2)
Traceback (most recent call last):

  File "/tmp/ipykernel_86038/2392625181.py", line 1, in <module>
    b=json.loads(dict_str_2)

  File "/home/thomp/miniconda3/envs/qutip/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)

  File "/home/thomp/miniconda3/envs/qutip/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/home/thomp/miniconda3/envs/qutip/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value
```

The error is caused by the always_shown section, which is
```
d='{"always_shown": [("sample_VRS_filtered.SampleVRSFiltered.freq_vrs_probe", ""), ("sample_VRS_filtered.SampleVRSFiltered.attenuation", ""), ("sample_VRS_filtered.SampleVRSFiltered.amplitude", ""), ("sample_VRS_filtered.SampleVRSFiltered.freq_rCav_offset", ""), ("sample_VRS_filtered.SampleVRSFiltered.t_sample_delay", "")]}'
```
all other parts of the `dict_str_2` string are correct and don't cause errors when converting into a dictionary with json.loads().

I only want to import the parameter overrides, but the error makes it hard to do that in an automated fashion

**Comment by dnadlinger** [comment]
`ndscan_params` is not actually JSON, but PYON. I've used regular JSON for the various schemata in the dataset to increase compatibility with various analysis environments, but the argument value is actually PYON, as most other things in ARTIQ.

You could use [exctract_param_schema()](https://github.com/OxfordIonTrapGroup/ndscan/blob/a1bb5246ec417b2377a373928917c1f54cbb98b6/ndscan/results/arguments.py#L10-L21) from the fledling `ndscan.results.*` tree. Right now, there isn't much but a few functions to pretty-print the scan ranges/overrides in `ndscan.show` or an analysis script.

**Comment by vmsch** [comment]
That worked, thank you!
