### ISSUE TITLE
Performance issues with device_setup and subscans

### ISSUE THREAD

**Issue by mbirtwell** [OxfordIonTrapGroup/ndscan#288]
We've hit a case where we're seeing suboptimal performance with subscans, because of unnecessary compilations (and execution) of `device_setup` methods.

Consider the following pseudocode:

```python
import artiq.experiment as aq
from artiq.experiment import kernel
import ndscan.experiment as nd

class Exp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_device('core')
        self.setattr_device('ttl0')

        self.setattr_param(
            "t_pulse",
            nd.FloatParam,
            "Pulse duration",
            default=1 * aq.ms,
            min=0.0,
            unit="ms",
        )

    @kernel
    def device_setup(self):
        self.ttl0.pulse(self.t_pulse.get())

    @kernel
    def run_once(self):
        self.ttl.on()

class SubscanExp(nd.ExpFragment):
    def build_fragment(self):
        self.setattr_fragment('exp', Exp)
        self.setattr_param_rebind("t_pulse", self.exp)

        nd.setattr_subscan(
            self,
            "scan",
            self.exp,
            [(self.exp, "t_pulse")],
            expose_analysis_results=True,
        )

    # def device_setup(self):
    #     pass

    def run_once(self):
        coord_gen = nd.LinearGenerator(
            0.0, 1.0 * aq.ms, , randomise_order=True
        )
       self.scan.run([(self.exp.t_pulse, coord_gen)])

ScanSubscanExp = nd.make_fragment_scan_exp(SubscanExp)
```

`ScanSubscanExp ` is run on the host. Without the commented out `device_setup` implementation, `exp.device_setup` is called before the subscan starts. This results in an unnecessary compilation / hardware access. The performance impact of this is magnified if `Exp` has multiple `subfragments`, each of which has a `device_setup` running on the coredevice and `Exp` doesn't have a `device_setup` because we then have to do separate compilations for the `device_setup`s .

If you use subscans to do an `NxM` scan you'll get `N` calls to the root experiment's `device_setup`, which by default will unnecessarily call `device_setup` of the fragment being scanned. And because those calls are initiated from the host rather than the kernel you could get up to `Nx(F-1)` compilations where `F` is the number of sub fragments that your experiment uses. The full `F-1` term is quite hard to achieve and depends how the branching of subfragment tree occurs. In one real-world case that term was coming out as 15 compilations per sub-scan run and there were 153 subfragments.

**Comment by dnadlinger** [comment]
Yes; we internally just always had explicitly empty `{host,device}_{setup,cleanup}()` implementations, but it is indeed best taken care of in ndscan itself. If you've got additional subfragments in the fragment doing the subscan, you might need to manually `detach_fragment` them still, though.

**Comment by hartytp** [comment]
ace, thanks @dnadlinger !

> If you've got additional subfragments in the fragment doing the subscan, you might need to manually detach_fragment them still, though.

Do you have an example in mind for when this situation might arise?

**Comment by dnadlinger** [comment]
> Do you have an example in mind for when this situation might arise?

Something like

```py
class TopLevel(ExpFragment):
  def build_fragment(self):
    self.setattr_fragment("impl", GateImplementation)
    self.setattr_fragment("algorithm", MyAlgorithm, self.impl)
    setattr_subscan(self, "scan", self.algorithm, …)
```

This requires attention anyway, as there is no way for the subscan to know that the gate implementation, which exists outside the scanned algorithm subtree, might need to be set up/…. The fragment would continue to be called from the TopLevel fragment's auto-generated setup and teardown methods.

Really, this boils down to subscan fragments which contain more than just the scanned fragment and the scan definition being a bit of an anti-pattern, and the reason I didn't address the original issue discussed here for a long time, as I thought I might change the design altogether.

**Comment by hartytp** [comment]
Thanks for clarifying @dnadlinger.

> Something like
> This requires a lot of care anyway, as there is no way for the subscan to know that the gate implementation, which exists outside the scanned algorithm subtree, might need to be set up/…. The fragment would continue to be called from the TopLevel fragment's auto-generated setup and teardown methods.

FWIW I've moved away from passing classes as arguments to `build_fragment` (partially in response to issues around FQNs) and tend to prefer to specialise the classes using something more like

```python
class TopLevel(ExpFragment):
  def build_fragment(self):
    class Algo(MyAlgorithm):
        gate_class = GateImplementation
    self.setattr_fragment("algorithm", Algo)
    setattr_subscan(self, "scan", self.algorithm, …)
```

> Really, this boils down to subscan fragments which contain more than just the scanned fragment and the scan definition being a bit of an anti-pattern

Worth a sentence or two in the subscan docs to point this out?

> the reason I didn't address the original issue discussed here for a long time, as I thought I might change the design altogether.

I agree with this line of thinking. What would a changed design look like? Something like a `SubscanExp` subclass of `ExpFragment`? This would allow us to do things like override `setattr_fragment` to raise an exception to forbid the anti-pattern discussed above.

**Comment by dnadlinger** [comment]
> FWIW I've moved away from passing classes as arguments to build_fragment 

This is certainly possible, and we also employ a similar pattern in several cases. I can't quite shake the feeling that this isn't the most natural corner of the design space, though (e.g. it's hard to discover what to supply, compared to a parameter list hint in a graphical editor).

> Worth a sentence or two in the subscan docs to point this out?

Sure, if you've got a better good idea of what exactly the advice should be.

> I agree with this line of thinking. What would a changed design look like? 

My main motivation for a redesign (or additional subscan-specialised fragment class) would actually be to allow subscan execution to be optimised, such that e.g. a 1D scan of a fragment with a 1D subscan is excecuted as a 2D scan on a single kernel, with the analysis results/… automatically being patched up to keep the result structure the same (e.g. for a post-cooling delay scan in a thermometry -> heating rate experiment). With compile times around 10 s for our more complex experiments, the extra compiler overhead tends to get somewhat annoying right now.

I'm not sure hwo the design would look in detail yet, but this would certainly be a major influence.

**Comment by mbirtwell** [comment]
I was just looking at how this was done for my own interest. If I understand it right on subscan.py line 239 we have `owner._detached_subfragments.add(fragment)`, which I think it redundant given the call to `owner.detach_fragment(fragment)` earlier in the function.

**Comment by dnadlinger** [comment]
Yes, this was indeed a leftover from refactoring, and is already gone (https://github.com/OxfordIonTrapGroup/ndscan/commit/2c421e340f73796218248ad5799e1c92071d4bdd).

**Comment by hartytp** [comment]
> This is certainly possible, and we also employ a similar pattern in several cases. I can't quite shake the feeling that this isn't the most natural corner of the design space, though (e.g. it's hard to discover what to supply, compared to a parameter list hint in a graphical editor).

I agree. It's also not the way I would naturally write code, but having class types mangled into fqns has also proved annoying in some cases so it's a bit of a compromise. Another pattern which maybe solves for both of our concerns is 
```python
class TopLevel(ExpFragment):
  def build_fragment(self):
    class Algo(MyAlgorithm):
        def build_fragment(self):
            super().build_fragment(GateImplementation)
    self.setattr_fragment("algorithm", Algo)
    setattr_subscan(self, "scan", self.algorithm, …)
```

> I'm not sure hwo the design would look in detail yet, but this would certainly be a major influence.

That makes sense and would be a really nice improvement.
