### ISSUE TITLE
Scans for enumerated values/bools

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/ndscan#30]
In some instances, it would be mildly useful to scan across the values of an enum or true/false for a boolean to compare the resulting curves. This might or might not be worth implementing in ndscan, though, as launching a few scans manually isn't too tricky.

**Comment by pmldrmota** [comment]
Bare-bones bool scans proposed in #374.

**Comment by dnadlinger** [comment]
Scans for BoolParams and simple exhaustive scans for EnumParams have been implemented for a while (e.g. ae4b27604d4155c7554a63359806ddeee48272af).
