### ISSUE TITLE
race in dataset janitor

### ISSUE THREAD

**Issue by hartytp** [OxfordIonTrapGroup/ndscan#311]
I believe there is a race in the dataset janitor. My understanding of the situation is as follows:
- There is a [subscriber](https://github.com/OxfordIonTrapGroup/ndscan/blob/7116e4a75c667fdaa0306f88b0fae1370fca16b0/ndscan/dataset_janitor.py#L182) which stores a mirror of the dataset db in [`dataset_keys`](https://github.com/OxfordIonTrapGroup/ndscan/blob/7116e4a75c667fdaa0306f88b0fae1370fca16b0/ndscan/dataset_janitor.py#L178)
- Separately, we store a dictionary of rids scheduled for deletion. `deletions`. The deletions dictionary is added to every time a new rid is scheduled by [subscribing](https://github.com/OxfordIonTrapGroup/ndscan/blob/7116e4a75c667fdaa0306f88b0fae1370fca16b0/ndscan/dataset_janitor.py#L203) go the scheduler.
- This mirror can easily get stale (particularly if the dataset db gets large for any reason so broadcasting it becomes slow)
- In the main loop, so long as there are items scheduled for deletion, we [try to delete](https://github.com/OxfordIonTrapGroup/ndscan/blob/7116e4a75c667fdaa0306f88b0fae1370fca16b0/ndscan/dataset_janitor.py#L244) all entries from the local mirror that begin with the ndscan prefix. Once we've deleted an item we pop it from the deletions list...
- however we do not pop them from `dataset_keys`. This results in a race where we can attempt to delete the same items many times

**Comment by dnadlinger** [comment]
I also haven't checked exactly in which case multiple attempts would occur, as only the keys starting with the respective rid prefix are chosen, which is then removed from `deletions`.

**Comment by hartytp** [comment]
> I also haven't checked exactly in which case multiple attempts would occur, as only the keys starting with the respective rid prefix are chosen, which is then removed from deletions.

Right, but the issue, as I understand it is that `deletions` is separate (separate subscriber) to `dataset_keys`. As long as there is anything scheduled for deletion we try to delete everything in `dataset_keys`, but we only pop from `deletions`. If the two get out of sync for any reason we end up doing a lot of spurious deleting.

As a bit of additional context here, the reason I came across this is that we got into one of those "so many datasets that the dashboard barely starts" situations with the janitor frantically trying to delete the same datasets.

**Comment by hartytp** [comment]
It's possible that there is a second bug here (e.g. the subscriber for the dataset db has died or something). Is there any harm in at least removing the result from `dataset_keys` when we hit that exception?

**Comment by hartytp** [comment]
hmm...it's also possible that the issue here is that we only handle `delete` and `set` events in the dataset_db subscriber

https://github.com/OxfordIonTrapGroup/ndscan/blob/7116e4a75c667fdaa0306f88b0fae1370fca16b0/ndscan/dataset_janitor.py#L168-L169

If I'm reading this correctly, a `pop` event will lead to phantom entries doomed to be deleted for eternity...

**Comment by hartytp** [comment]
Whatever the cause, it feels like a reasonable defensive precaution to remove entries from the dataset mirror once the master tells us that they no longer exist.

**Comment by dnadlinger** [comment]
> with the janitor frantically trying to delete the same datasets.

A loop with the same datasets attempting to be deleted over and over again should be impossible if the deletion logic works as intended (whether the local dataset view is in sync or not), as the respective rid prefix is removed from `deletions` once the loop is done. Perhaps there was some issue causing something else than a `KeyError` that was not handled correctly?

> Whatever the cause, it feels like a reasonable defensive precaution to remove entries from the dataset mirror once the master tells us that they no longer exist.

That doesn't sound unreasonable, though I'm not sure it will fix your issue (see above).

**Comment by hartytp** [comment]
> A loop with the same datasets attempting to be deleted over and over again should be impossible if the deletion logic works as intended (whether the local dataset view is in sync or not), as the respective rid prefix is removed from deletions once the for key in to_remove loop is done. Perhaps there was some issue causing something other than a KeyError, and the intended recovery path did not handle this correctly?

Apologies, yes, thanks for the correction. I had misread the logic here and I have, indeed, misdiagnosed the underlying issue.

I need to dig into this further, but I think the issue is actually the way we're removing elements from `deletions`. Consider this test case which, I think, reflects what the janitor is doing

```python
deletions = dict()
for i in range(10):
  deletions[i] = i
  
while deletions:
  rid, timestamp = next(iter(deletions.items()))
  print(rid, timestamp)
  deletions.popitem()
```

This prints
```python
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
```

So I think the issue is that we're not removing the rid from `deletions` that we're deleting the datasets for.

**Comment by dnadlinger** [comment]
Oh, what a blind spot! Thanks.

**Comment by hartytp** [comment]
Thanks for calling BS on my original explation!

**Comment by hartytp** [comment]
BTW it's not obvious to me that there isn't still a residual race condition here. What if we delete a rid before the dataset subscriber has alerted us about the existence of its datasets in the first place? AFAICT in that case, we never the rid datasets until the janitor/master is restarted.

**Comment by dnadlinger** [comment]
IIRC that particular case should be fine for reasonable deletion delays, as the datasets are only filtered when the timeout has elapsed.

**Comment by dnadlinger** [comment]
(It really seems like for what it does, this code should be more straightforward.)

**Comment by hartytp** [comment]
> (It really seems like for what it does, this code should be more straightforward, though.)

state is hard...

> IIRC that particular case should be fine for reasonable deletion delays, as the datasets are only filtered when the timeout has elapsed.

True. I think I'm a bit traumatised as our dataset db has reached hundreds of k lines so the delay is many seconds even over a local link...the current code is probably fine now we've fixed the deletion issue. I'll think again with a fresh head in the morning

**Comment by dnadlinger** [comment]
(I do wonder how this even appeared to work in the first place, though; we've been running like this for a long time!)
