### ISSUE TITLE
"No module named 'wrapt'" in pip install on a Julia-managed Conda install

### ISSUE THREAD

**Issue by ljstephenson** [OxfordIonTrapGroup/ndscan#342]
Pip install doesn't work since the removal of `setup.py` and switch to poetry in 93d7366

Unsuccessful output:
```
(artiq-ndscan-8) C:\Users\ljs3>pip install git+https://github.com/OxfordIonTrapGroup/ndscan.git@93d73665390b74af8b11dcc3543c81872c7f137c
Collecting git+https://github.com/OxfordIonTrapGroup/ndscan.git@93d73665390b74af8b11dcc3543c81872c7f137c
  Cloning https://github.com/OxfordIonTrapGroup/ndscan.git (to revision 93d73665390b74af8b11dcc3543c81872c7f137c) to c:\users\ljs3\appdata\local\temp\pip-req-build-zk244dau
  Running command git clone --filter=blob:none --quiet https://github.com/OxfordIonTrapGroup/ndscan.git 'C:\Users\ljs3\AppData\Local\Temp\pip-req-build-zk244dau'
  Running command git rev-parse -q --verify 'sha^93d73665390b74af8b11dcc3543c81872c7f137c'
  Running command git fetch -q https://github.com/OxfordIonTrapGroup/ndscan.git 93d73665390b74af8b11dcc3543c81872c7f137c  Running command git checkout -q 93d73665390b74af8b11dcc3543c81872c7f137c
  Resolved https://github.com/OxfordIonTrapGroup/ndscan.git to commit 93d73665390b74af8b11dcc3543c81872c7f137c
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Fatal Python error: init_import_site: Failed to import the site module
      Python runtime state: initialized
      Traceback (most recent call last):
        File "C:\Users\ljs3\.julia\conda\3\envs\artiq-ndscan-8\lib\site.py", line 617, in <module>
          main()
        File "C:\Users\ljs3\.julia\conda\3\envs\artiq-ndscan-8\lib\site.py", line 610, in main
          execsitecustomize()
        File "C:\Users\ljs3\.julia\conda\3\envs\artiq-ndscan-8\lib\site-packages\certifi_win32\bootstrap.py", line 37, in _execsitecustomize
          _register_bootstrap_functions()
        File "C:\Users\ljs3\.julia\conda\3\envs\artiq-ndscan-8\lib\site-packages\certifi_win32\bootstrap.py", line 25, in _register_bootstrap_functions
          from . import wrapt_certifi
        File "C:\Users\ljs3\.julia\conda\3\envs\artiq-ndscan-8\lib\site-packages\certifi_win32\wrapt_certifi.py", line 3, in <module>
          import wrapt
      ModuleNotFoundError: No module named 'wrapt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Note that `wrapt` is definitely installed:
```
(artiq-ndscan-8) C:\Users\ljs3>python -c "import wrapt; print(wrapt.__version__)"
1.14.1
```

and installing from the previous commit ddf8151 does work:
```
(artiq-ndscan-8) C:\Users\ljs3>pip install git+https://github.com/OxfordIonTrapGroup/ndscan.git@ddf81517c0751f66fd00515a80ffbbccee7c46bb
Collecting git+https://github.com/OxfordIonTrapGroup/ndscan.git@ddf81517c0751f66fd00515a80ffbbccee7c46bb
  Cloning https://github.com/OxfordIonTrapGroup/ndscan.git (to revision ddf81517c0751f66fd00515a80ffbbccee7c46bb) to c:\users\ljs3\appdata\local\temp\pip-req-build-pchkgj52
  Running command git clone --filter=blob:none --quiet https://github.com/OxfordIonTrapGroup/ndscan.git 'C:\Users\ljs3\AppData\Local\Temp\pip-req-build-pchkgj52'
  Running command git rev-parse -q --verify 'sha^ddf81517c0751f66fd00515a80ffbbccee7c46bb'
  Running command git fetch -q https://github.com/OxfordIonTrapGroup/ndscan.git ddf81517c0751f66fd00515a80ffbbccee7c46bb
  Running command git checkout -q ddf81517c0751f66fd00515a80ffbbccee7c46bb
  Resolved https://github.com/OxfordIonTrapGroup/ndscan.git to commit ddf81517c0751f66fd00515a80ffbbccee7c46bb
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyqtgraph>=0.12.4 in c:\users\ljs3\.julia\conda\3\envs\artiq-ndscan-8\lib\site-packages (from ndscan==0.3.0) (0.13.1)
Requirement already satisfied: numpy>=1.20.0 in c:\users\ljs3\.julia\conda\3\envs\artiq-ndscan-8\lib\site-packages (from pyqtgraph>=0.12.4->ndscan==0.3.0) (1.25.2)
Building wheels for collected packages: ndscan
  Building wheel for ndscan (setup.py) ... done
  Created wheel for ndscan: filename=ndscan-0.3.0-py3-none-any.whl size=123959 sha256=f9f033586ed0ecef4f12353d0031b849bc728ed4de7c860c6be697bfa440cffc
  Stored in directory: c:\users\ljs3\appdata\local\pip\cache\wheels\e9\57\9a\c04164abf4d6b7a3bdd3d001e5eba09026513a5aa3179d353a
Successfully built ndscan
Installing collected packages: ndscan
Successfully installed ndscan-0.3.0
```

I may be able to investigate this further next week depending on US government shutdown status, but in the meantime is there a simple way around this that I'm missing? Haven't had the chance to delve into poetry at all yet.

**Comment by dnadlinger** [comment]
Oh dear; no, this isn't something I've encountered (on Windows 10 and the official python.org binaries, macOS, and Linux via Nix). It looks like some kind of "internal error", rather than a dependency ndscan would pull in directly (i.e. triggered by depending on `poetry-core`, rather than any of the actual ndscan dependencies).

I suppose you could always locally revert back to setup.py, or change back to https://github.com/OxfordIonTrapGroup/ndscan/tree/release-0.3. NB: `master` will also depend on a recent (pre-release) ARTIQ version, as the applet API has changed. As with Poetry, I'm quite keen on keeping the maintenance load minimal by not supporting more than one configuration if possible. Of course, this does require that one solution to be reasonably compatible out in the wild, but this particular issue really seems more like some kind of unfortunate bug in Conda. They managed to outright break a standard library module before (lzma, by breaking the xz package), so I wouldn't be terribly surprised…

**Comment by dnadlinger** [comment]
Just tried using the exact command on a Python 3.10/Windows 10 install in a fresh venv (`python -m venv test-venv; test-venv\Scripts\activate; C:\Scratch>python -m venv test-venv; pip install git+https://github.com/OxfordIonTrapGroup/ndscan.git@master`), and it completes just fine. (You do need to manually provide `artiq` on Windows now, as it's not on PyPI, and specifying a Git dependency seems to mean that only that particular revision is acceptable, which is a problem for composing multiple packages together.)

**Comment by ljstephenson** [comment]
Thanks for checking so quickly! It's not specific to julia managed conda, I also get the same error on another machine that didn't get quite as convoluted an install path, but I agree that a conda bug seems like a very likely root cause.

Totally with you on only maintaining one configuration, I'll try a few more things out soon and link back to here if I can root cause it to something in conda.

A local setup.py will probably suit me until I can investigate, thank you!

**Comment by dnadlinger** [comment]
Please do keep me posted; being able to install ndscan into Conda environments is definitely desirable!

**Comment by ljstephenson** [comment]
Woof; I have been previously using a batch script to do all my conda installs with a bunch of extra dependencies (I know, I know, it's not clean at all but for a few machines it works ok). If I reduce my script to just the following:

```
call conda create -n artiq-ndscan-8 --override-channels^
 -c https://conda.m-labs.hk/artiq-beta^
 -c defaults^
 -c conda-forge^
 -y^
 python=3.10^
 artiq=8^
 || exit /b %errorlevel%
call conda activate artiq-ndscan-8      || exit /b %errorlevel%
pip install git+https://github.com/OxfordIonTrapGroup/ndscan.git
```

...then the pip install command completes successfully. Yet another case of conda breaking something in weird and wonderful ways! No idea how it ended up that broken, I can share the original script in all it's glory if you'd like but there's nothing obvious in there that would appear to cause this.

Happy to close this issue; perhaps maybe with a little word of warning in docs about how fussy conda installs can be.
