### ISSUE TITLE
xy_1d: computed_curve CustomAnalysis annotations no longer shown

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/ndscan#362]
A `computed_curve` returned from a `CustomAnalysis` no longer shows up on c2a2c07dafadfe55c11b43b691a3c3a5dbac6829. `location` annotation still do.

ndscan_show or re-opening the applet doesn't coax out the curves either.

This is likely related to the recent channel hiding/… changes.

Internal reproducer `alice_540050`.

**Comment by pmldrmota** [comment]
I noticed similar behaviour with `OnlineFit`, which is only shown while the data is accumulated and then disappears. Is this related?

**Comment by pmldrmota** [comment]
Closed with 3be9a9ed5a2dec24bd749b55fecedb18e78a83fe.
