### ISSUE TITLE
Cursor labels unreadable on bright 2D-scan data points

### ISSUE THREAD

**Issue by pmldrmota** [OxfordIonTrapGroup/ndscan#404]
As in this screenshot:

![20240503_190730~2](https://github.com/OxfordIonTrapGroup/ndscan/assets/49479443/ad05cebb-ebde-486d-98dd-fa6d45844ca4)

It would be nice if the colour of the coordinate labels would change depending on the background.
Note that the crosshair itself is already doing this correctly.

I tried setting the `QPainter.CompositionMode_Xor` property on the `painter` of `CrosshairLabel.paint(painter, *_)` before painting, and the colour of the text changes depending on the mode, but consistent with a constant background colour. This leads me to believe that the `pyqtgraph` 2D plot is painted using a different `painter` than the `CrosshairLabel`, or at different times, or so.
It seems the `QtCore.Qt.CursorShape.CrossCursor` isn't even painted in `Qt`, so the approach seems completely different.

**Comment by dnadlinger** [comment]
Yep, this has also been on my radar. Something like QPainter.CompositionMode_Xor is a great suggestion. If that does not work, maybe we can add a black outline to the white text instead; then it would work on either background.

**Comment by dnadlinger** [comment]
And yes, I think the cursor is painted by the OS.

**Comment by dnadlinger** [comment]
It seems like QGraphicsView might in general render different items into a buffer first before combining them, see e.g. https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/graphicsview/qgraphicsscene.cpp?h=dev#n4229. This, by the way, is the only mention of CompositionMode in all of `src/widgets/graphicsview`, so it does not seems likely it is supported.

**Comment by dnadlinger** [comment]
This works, but makes the cursor laggy for reasons I don't quite understand:
```py
    def paint(self, painter: QPainter, option: QtWidgets.QStyleOptionGraphicsItem, widget: QtWidgets.QWidget):
        self.setPen(self.outline_pen)
        super().paint(painter, option, widget)
        self.setPen(self.nothing_pen)
        super().paint(painter, option, widget)
```
Even with either of the two duplicates in, i.e. still overwriting it in Qt and setting the pen every time, this still runs perfectly smoothly. Perhaps painting twice is thrashing some cache?

Maybe the solution is just to make two QGraphicsSimpleTextItems on top of each other.

**Comment by pmldrmota** [comment]
Have you tried `setPen()` and `setBrush()` together on the same `QGraphicsSimpleTextItem`, as described [here](https://doc.qt.io/qt-6/qgraphicssimpletextitem.html#:~:text=The%20simple%20text%20item%20can,items%20with%20long%20text%20content.)?
They also state that drawing the outline can be slow.
