### ISSUE TITLE
Support overriding parameters with custom stores

### ISSUE THREAD

**Issue by hartytp** [OxfordIonTrapGroup/ndscan#408]
It would be nice to be able to do things like `self.fragment.override("param", store_class=LambdaStore, fun=labmda: ...)` where `LambdaStore` is a (user-defined) subclass of `ParameterStore`. This would allow, for example, users to specify relationships between parameters in a simple way.

**Comment by dnadlinger** [comment]
Agreed that this would be nice to have.

Implemented straightforwardly as described here, wouldn't this run into trouble with polymorphism due to some e.g. `FloatParam.store`s still referring to `FloatParamStore` instances while the overridden `FloatParam` refers to `LambdaStore`?

**Comment by hartytp** [comment]
aah, thanks @dnadlinger - you're right about that (and my prototype was too simple to pick that up). I'm not sure if there is a nice design possible in this area once that limitation is taken into account...

**Comment by hartytp** [comment]
I don't see a way of implementing this kind of feature given the limits of artiq python so closing.
