### ISSUE TITLE
Define parameter as always fixed

### ISSUE THREAD

**Issue by hartytp** [OxfordIonTrapGroup/ndscan#70]
Some parameters should be settable, but not scannable (so that the experiment always runs as if that parameter was set to "fixed" in the drop-down menu in the dashboard). This might be useful for setting the number of scan points, for example, which is never intended to be scanned over.

**Comment by dnadlinger** [comment]
Note for later: The parameter for setting this should be an enum that represents how parameters can be scanned – from the core device, host-only (once implemented), or not at all.

**Comment by dnadlinger** [comment]
Actually, no, it shouldn't; the host_setup/device_setup distinction applies also outside scans.
